name: Build Plugin Archive

on:
  release:
    types: [created]

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install tar (if needed)
        run: sudo apt-get update && sudo apt-get install -y tar gzip

      - name: Extract plugin name and version from tag
        id: vars
        run: |
          TAG="${GITHUB_REF##*/}"
          PLUGIN_NAME="${GITHUB_REPOSITORY##*/}"
          echo "plugin_name=${PLUGIN_NAME}" >> $GITHUB_OUTPUT
          echo "version=${TAG}" >> $GITHUB_OUTPUT

      - name: Build tar.gz excluding node_modules and package-lock.json
        run: |
          PLUGIN="${{ steps.vars.outputs.plugin_name }}"
          VERSION="${{ steps.vars.outputs.version }}"
          ARCHIVE_NAME="${PLUGIN}-${VERSION}.tar.gz"

          echo "Creating archive: $ARCHIVE_NAME"

          tar --exclude="*/node_modules" \
              --exclude="*/package-lock.json" \
              -czf "$ARCHIVE_NAME" "$PLUGIN"

      - name: Upload archive to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ steps.vars.outputs.plugin_name }}-${{ steps.vars.outputs.version }}.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
